src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt
src/main/kotlin/no/nav/syfo/application/database/Database.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/OppfolgingstilfelleService.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/OppfolgingstilfelleBitService.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/Oppfolgingstilfellebit.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/database/NoElementInsertedException.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/database/OppfolginsgtilfelleBitQuery.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/database/domain/PNarmesteLederRelasjon.kt
src/main/kotlin/no/nav/syfo/util/DateUtil.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/OppfolgingstilfelleServiceSpek.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleApiSpek.kt

Store OppfolgingstilfelleBit in database manually until kafka-logic is implemented.

Create and get OppfolgingstilfelleBit from database

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
build.gradle.kts
src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironmentKafka.kt
src/main/kotlin/no/nav/syfo/application/backgroundtask/BackgroundTask.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/Oppfolgingstilfellebit.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/kafka/KafkaConfig.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/kafka/KafkaSyketilfelleBitMetric.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/kafka/KafkaSyketilfelleBitTask.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/kafka/KafkaSyketilfellebit.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/kafka/KafkaSyketilfellebitDeserializer.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/database/NoElementInsertedException.kt
src/main/kotlin/no/nav/syfo/util/RequestUtil.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleApiSpek.kt
src/test/kotlin/testhelper/ExternalMockEnvironment.kt
src/test/kotlin/testhelper/TestEnvironment.kt
src/test/kotlin/testhelper/TestKafka.kt
src/test/kotlin/testhelper/generator/KafkaSyketilfellebitGenerator.kt

Only an implementation of the reading and storing of records from the topic. The Kafka functionality is turned off with a toggle until it is ready for dev and/prod.
Functionality for duplicates/idempotence is added later.

Read SyketilfelleBit from Kafka and store in database

---

.github/workflows/kafka-oppfolgingstilfelle.yaml
.nais/kafka/dev.json
.nais/kafka/oppfolgingstilfelle.yaml
.nais/kafka/prod.json
README.md

Create a topic for Oppfolgingstifelle. Use four partitions for good consumer performance.

Create topic for Oppfolgingstilfelle

---

src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/application/kafka/KafkaConfig.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/OppfolgingstilfelleService.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/kafka/KafkaConfig.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/domain/OppfolgingstilfelleArbeidstaker.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaConfig.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfelleArbeidstaker.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfelleSerializer.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/OppfolgingstilfelleProducer.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleApiSpek.kt
src/test/kotlin/testhelper/TestApiModule.kt

Også refaktorert til noe felles kafka-config for consumer og producer

Produsere oppfolgingstilfelle for arbeidstaker til kafka topic

---

src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/domain/OppfolgingstilfelleDag.kt

Add virksomhetsnummerList to all Oppfolgingstilfelle, not only the last.

Fix and simplify groupOppfolgingstilfelleList

---

.nais/kafka/oppfolgingstilfelle.yaml
README.md
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/OppfolgingstilfelleService.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleApi.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/api/domain/OppfolgingstilfellePersonDTO.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/Oppfolgingstilfellebit.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/kafka/KafkaSyketilfellebitService.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/database/OppfolgingstilfelleQuery.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/database/POppfolgingstilfellePerson.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/domain/OppfolgingstilfellePerson.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePerson.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfelleSerializer.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/OppfolgingstilfelleProducer.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleApiSpek.kt
src/test/kotlin/testhelper/UserConstants.kt
src/test/kotlin/testhelper/generator/KafkaSyketilfellebitGenerator.kt
src/test/kotlin/testhelper/generator/OppfolgingstilfelleBitGenerator.kt
src/test/kotlin/testhelper/mock/SyfoTilgangskontrollMock.kt

Reflect that Oppfolgingstilfelle can also be for a person that is not Arbeidstaker, in addition to Arbeidstaker.

Rename OppfolgingstilfelleArbeidstaker to OppfolgingstilfellePerson

---

src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/OppfolgingstilfelleService.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/api/domain/OppfolgingstilfellePersonDTO.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/Oppfolgingstilfellebit.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/kafka/KafkaSyketilfellebit.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/domain/OppfolgingstilfelleDag.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/domain/OppfolgingstilfellePerson.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/kafka/KafkaOppfolgingstilfellePerson.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleApiSpek.kt
src/test/kotlin/testhelper/generator/KafkaSyketilfellebitGenerator.kt

Add arbeidstakerAtTilfelleEnd show wether or not a person is Arbeidstaker at the end of the Oppfolgingstilfelle.

Add arbeidstakerAtTilfelleEnd to OppfolgingstilfellePerson

---

src/main/resources/db/migration/R__grant_to_cloudsqliamuser.sql
src/main/resources/db/migration/V1_4__create_user_isyfoanalyse.sql

Create database user isyfo-analyse for analytical purposes and grant the user access to read from all tables in database.

Create user Isyfo-analyse and grant acsess

---

src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt
src/main/kotlin/no/nav/syfo/application/cache/ApplicationEnvironmentRedis.kt
src/main/kotlin/no/nav/syfo/application/cache/RedisStore.kt
src/main/kotlin/no/nav/syfo/application/database/DatabaseEnvironment.kt
src/main/kotlin/no/nav/syfo/application/database/DatabaseModule.kt
src/main/kotlin/no/nav/syfo/application/kafka/KafkaConfig.kt
src/main/kotlin/no/nav/syfo/application/kafka/KafkaEnvironment.kt
src/main/kotlin/no/nav/syfo/client/azuread/AzureAdClient.kt
src/main/kotlin/no/nav/syfo/client/azuread/AzureEnvironment.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/kafka/KafkaConfig.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/kafka/KafkaSyketilfelleBitTask.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/kafka/KafkaConfig.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleApiSpek.kt
src/test/kotlin/testhelper/ExternalMockEnvironment.kt
src/test/kotlin/testhelper/TestEnvironment.kt
src/test/kotlin/testhelper/TestRedis.kt

Move environment variables for AzureAD, Psql-dataase and Redis into separate classes for improved readiblity.

Move environment variables into separate classes

---

src/main/kotlin/no/nav/syfo/client/HttpClientCommon.kt

Ref: https://ktor.io/docs/migrating-2.html#response-validation

httpClient expects success

---

src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/application/api/ApiFeature.kt
src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt
src/main/kotlin/no/nav/syfo/application/api/access/APIConsumerAccessService.kt
src/main/kotlin/no/nav/syfo/application/api/access/ForbiddenAccessSystemConsumer.kt
src/main/kotlin/no/nav/syfo/application/api/access/PreAuthorizedApplication.kt
src/main/kotlin/no/nav/syfo/application/api/authentication/TokenAuth.kt
src/main/kotlin/no/nav/syfo/client/azuread/AzureEnvironment.kt
src/main/kotlin/no/nav/syfo/narmesteleder/api/OppfolgingstilfelleNarmesteLederApi.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/OppfolgingstilfelleService.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/api/OppfolgingstilfellePersonApi.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/api/OppfolgingstilfellePersonSystemApi.kt
src/test/kotlin/no/nav/syfo/narmesteleder/api/OppfolgingstilfelleNarmesteLederApiSpek.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleApiSpek.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleSystemApiSpek.kt
src/test/kotlin/testhelper/JWTUtil.kt
src/test/kotlin/testhelper/TestEnvironment.kt

Trenger et system-api her siden isdialogmote får en cronjob som trenger å gjøre dette oppslaget.

Add system-api

---

src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/domain/Oppfolgingstilfellebit.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/domain/OppfolgingstilfelleDag.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/domain/OppfolgingstilfellePerson.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/kafka/KafkaOppfolgingstilfellePerson.kt
src/test/kotlin/testhelper/generator/GenerateOppfolgingstilfellePerson.kt

Starter med et flagg for gradert på oppfølgingstilfellet som isaktivitetskrav kan bruke til å bestemme om aktivitetskrav skal vurderes. 
Kan forsøke meg på noen tester for dette etterpå.

Add gradertAtTilfelleEnd to OppfolgingstilfellePerson

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/client/ClientEnvironment.kt
src/main/kotlin/no/nav/syfo/client/arbeidsforhold/ArbeidsforholdClient.kt
src/main/kotlin/no/nav/syfo/client/arbeidsforhold/domain/AaregArbeidsforhold.kt
src/test/kotlin/no/nav/syfo/client/arbeidsforhold/ArbeidsforholdClientSpek.kt
src/test/kotlin/testhelper/ExternalMockEnvironment.kt
src/test/kotlin/testhelper/TestEnvironment.kt
src/test/kotlin/testhelper/mock/ArbeidsforholdMock.kt

Skal brukes til å finne arbeidsgiver for arbeidstaker i tilfelle-biter med tag SYKMELDING,NY som vi skal begynne å bruke

Aareg client

---

src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt
src/main/kotlin/no/nav/syfo/application/cronjob/CronjobModule.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/cronjob/SykmeldingNyCronjob.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/database/OppfolgingstilfelleBitQuery.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleApiSpek.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleSystemApiSpek.kt
src/test/kotlin/testhelper/TestApiModule.kt
src/test/kotlin/testhelper/TestEnvironment.kt
src/test/kotlin/testhelper/generator/KafkaSyketilfellebitGenerator.kt

Cronjob'en er ikke togglet ut, men vil ikke gjøre noe i prod før toggelen for lesing av SYKMELDING-NY er enabled.

Cronjob sykmelding ny

---

src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/OppfolgingstilfelleBitService.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/database/OppfolgingstilfelleBitQuery.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/database/domain/POppfolgingstilfelleBit.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/domain/Oppfolgingstilfellebit.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleApiSpek.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleSystemApiSpek.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/OppfolgingstilfelleBitSpek.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/cronjob/OppfolgingstilfelleCronjobSpek.kt
src/test/kotlin/testhelper/generator/OppfolgingstilfelleBitGenerator.kt

Siden korrekt lagring og bruk av korreksjons-feltet har blitt lagt på for litt siden mangler dette feltet for mange biter i databasen. Retter opp dette ved å reprosessere Kafka-topic'en fra starten snart.

Legg til korreksjonsfelt ved reprosessering der det mangler

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/kafka/KafkaSyketilfellebit.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/kafka/KafkaSyketilfellebitService.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleApiSpek.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleSystemApiSpek.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/cronjob/OppfolgingstilfelleCronjobSpek.kt
src/test/kotlin/testhelper/TestEnvironment.kt

Da tror jeg omsider alt er på plass for å konsumere sykmelding-ny i produksjon. 
Tenkte å la dette gå en stund for å se at det fungerer bra, men for å få med oss de som allerede skulle ha blitt kandidater må vi konsumere topic fra starten av - avventer det litt.

Enable sykmelding-ny in prod

---

.nais/naiserator-prod.yaml

Tar tid å jobbe i gjennom syketilfellebiter-topic'en på nytt - skalerer opp for å få det til å gå litt fortere.

Speed up reprocessing

---

src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/OppfolgingstilfelleService.kt
src/main/kotlin/no/nav/syfo/util/DateUtil.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleApiSpek.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleSystemApiSpek.kt
src/test/kotlin/testhelper/TestEnvironment.kt
src/test/kotlin/testhelper/generator/KafkaSyketilfellebitGenerator.kt

Ikke inkluder framtidige oppfolgingstilfeller i responsen fra api'ene.

Api filter oppfolgingstilfelle

---

src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/database/OppfolgingstilfelleBitQuery.kt

Holder ikke helt tritt med innkommende biter slik det er nå, så må øke størrelsen her.

Increase batch size for cronjob

---

src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt

Liten uteglemmelse i forrige PR

Grant access to api from isdialogmotekandidat

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
build.gradle.kts
src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/application/kafka/KafkaEnvironment.kt
src/main/kotlin/no/nav/syfo/identhendelse/kafka/IdenthendelseConsumerService.kt
src/main/kotlin/no/nav/syfo/identhendelse/kafka/KafkaIdenthendelseConsumerConfig.kt
src/main/kotlin/no/nav/syfo/identhendelse/kafka/KafkaIdenthendelseDTO.kt
src/main/kotlin/no/nav/syfo/identhendelse/kafka/KafkaIdenthendelseMetric.kt
src/main/kotlin/no/nav/syfo/identhendelse/kafka/KafkaIdenthendelseTask.kt
src/test/kotlin/testhelper/TestEnvironment.kt
src/test/kotlin/testhelper/TestKafka.kt

Starter med configen som må på plass.
Ikke fått tilgang i PDL enda 🚫

Add kafkaIdenthendelse-config

---

src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt
src/main/kotlin/no/nav/syfo/client/pdl/PdlClient.kt
src/main/kotlin/no/nav/syfo/client/pdl/domain/PdlIdenterResponse.kt
src/main/kotlin/no/nav/syfo/identhendelse/IdenthendelseService.kt
src/main/kotlin/no/nav/syfo/identhendelse/database/IdenthendelseQuery.kt
src/main/kotlin/no/nav/syfo/identhendelse/kafka/IdenthendelseConsumerService.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/database/OppfolgingstilfelleBitQuery.kt
src/test/kotlin/no/nav/syfo/identhendelse/IdenthendelseServiceSpek.kt
src/test/kotlin/testhelper/TestApiModule.kt
src/test/kotlin/testhelper/UserConstants.kt
src/test/kotlin/testhelper/generator/KafkaIdenthendelseDTOGenerator.kt
src/test/kotlin/testhelper/mock/PdlMock.kt

Add Identhendelse service

---

.github/workflows/dispatch.yaml
.github/workflows/main.yaml

En del feil i dev pga dette nå, så da bytter vi bare over. I tillegg så funker ikke `Check if built`-steget med `ghcr` så da kan det også fjernes at vi bygger en ekstra gang.

Change from docker.pkg to ghcr

---

src/main/kotlin/no/nav/syfo/personhendelse/PersonhendelseService.kt

Viser seg at hendelseid ikke er unik.. så må bruke vår egen randomuuid i stedet

Use random uuid

---

build.gradle.kts
src/main/kotlin/no/nav/syfo/client/pdl/domain/PdlIdenterResponse.kt
src/main/kotlin/no/nav/syfo/identhendelse/IdenthendelseService.kt
src/main/kotlin/no/nav/syfo/identhendelse/database/IdenthendelseQuery.kt
src/main/kotlin/no/nav/syfo/identhendelse/kafka/IdenthendelseConsumerService.kt
src/main/kotlin/no/nav/syfo/identhendelse/kafka/KafkaIdenthendelseConsumerConfig.kt
src/main/kotlin/no/nav/syfo/identhendelse/kafka/KafkaIdenthendelseTask.kt
src/test/kotlin/no/nav/syfo/identhendelse/IdenthendelseServiceSpek.kt
src/test/kotlin/testhelper/UserConstants.kt
src/test/kotlin/testhelper/generator/KafkaIdenthendelseDTOGenerator.kt
src/test/kotlin/testhelper/generator/OppfolgingstilfelleBitGenerator.kt

Her manglet vi å oppdatere ene tabellen + legger til unsubscribe av consumer ved feil. Funker i dev.

Add updates on identhendelse to all tables

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt

Cronjob'en i syfooversiktsrv har kjørt, så da kan vi ta bort dette igjen.

Remove API-access syfooversiktsrv

---

src/main/resources/db/migration/V2_7__correct_incorrect_sykmelding.sql

Dette skal korrigere FAGSYSTEM-272391.
Reprosesserer de to siste tilfellebitene siden de har samme inntruffet-tidspunkt.

Fix incorrect tom for old tilfellebiter

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
build.gradle.kts
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/OppfolgingstilfelleBitService.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/database/OppfolgingstilfelleBitQuery.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/kafka/KafkaSyketilfellebitService.kt
src/main/resources/db/migration/R__grant_to_cloudsqliamuser.sql
src/main/resources/db/migration/V2_8__create_table_oppfolgingstilfelle_bit_deleted.sql
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/cronjob/OppfolgingstilfelleCronjobSpek.kt
src/test/kotlin/testhelper/TestDatabase.kt
src/test/kotlin/testhelper/generator/KafkaSyketilfellebitGenerator.kt

Ref https://nav-it.slack.com/archives/CMF67JLRM/p1679396326866259

Tombstone records should be deleted

---

src/main/kotlin/no/nav/syfo/client/veiledertilgang/VeilederTilgangskontrollClient.kt
src/main/kotlin/no/nav/syfo/client/veiledertilgang/VeilederTilgangskontrollClientMetric.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/api/OppfolgingstilfellePersonApi.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/api/OppfolgingstilfellePersonSystemApi.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleApiSpek.kt
src/test/kotlin/testhelper/mock/SyfoTilgangskontrollMock.kt

For å kunne hente oppfølgingstilfeller for en liste av personer fra isdialogmotekandidat unntakstatistikk-api

Add api for getting oppfolgingstilfeller for persons

---

src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt
src/main/kotlin/no/nav/syfo/narmesteleder/api/OppfolgingstilfelleNarmesteLederApi.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/OppfolgingstilfelleService.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/api/OppfolgingstilfellePersonApi.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/api/OppfolgingstilfellePersonSystemApi.kt
src/main/kotlin/no/nav/syfo/personhendelse/PersonhendelseService.kt
src/main/kotlin/no/nav/syfo/personhendelse/kafka/KafkaPersonhendelseTask.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleApiSpek.kt
src/test/kotlin/no/nav/syfo/personhendelse/KafkaPersonhendelseConsumerServiceSpek.kt
src/test/kotlin/testhelper/TestApiModule.kt

Ref https://jira.adeo.no/browse/FAGSYSTEM-285454

Ikke bruk gamle identer når vi henter oppfølgingstilfeller

---

src/main/kotlin/no/nav/syfo/App.kt
src/main/kotlin/no/nav/syfo/client/pdl/PdlClient.kt
src/main/kotlin/no/nav/syfo/client/pdl/PdlClientMetric.kt
src/main/kotlin/no/nav/syfo/client/pdl/PdlPersonidentIdenterCache.kt
src/main/kotlin/no/nav/syfo/client/pdl/PdlPersonidentNameCache.kt
src/test/kotlin/no/nav/syfo/identhendelse/IdenthendelseServiceSpek.kt

Kom over noe ubrukt kode etter https://github.com/navikt/isoppfolgingstilfelle/pull/154

Delete unused code

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt

Allow isbehandlerdialog to use system api

IS-1738: Allow access isbehandlerdialog

---

src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/api/domain/OppfolgingstilfellePersonDTO.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/domain/OppfolgingstilfelleDag.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/domain/OppfolgingstilfellePerson.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/kafka/KafkaOppfolgingstilfellePerson.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleApiSpek.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/OppfolgingstilfelleBitSpek.kt
src/test/kotlin/testhelper/generator/GenerateOppfolgingstilfellePerson.kt

Lagt til telling av sykedager innenfor et oppfølgingstilfelle

IS-1864: Antall sykedager

---

src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/api/domain/OppfolgingstilfellePersonDTO.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/domain/OppfolgingstilfellePerson.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleApiSpek.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleSystemApiSpek.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/OppfolgingstilfelleBitSpek.kt

Kalkulerer antall uker relativt til dagens dato i rest-api'et.
(skal brukes i syfomodiaperson)

IS-1864: Calculate weeks

---

.nais/kafka/oppfolgingstilfelle.yaml

Se behov i slack: https://nav-it.slack.com/archives/C02NV48EB27/p1709819288631459

Give access to topic for dvh

---

.nais/naiserator-dev.yaml
.nais/naiserator-prod.yaml
src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/api/OppfolgingstilfelleArbeidstakerApi.kt
src/test/kotlin/no/nav/syfo/narmesteleder/api/OppfolgingstilfelleNarmesteLederApiSpek.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleArbeidstakerApiSpek.kt
src/test/kotlin/testhelper/TestEnvironment.kt

Se slack-tråd: https://nav-it.slack.com/archives/CGX6MF9S8/p1710141439479389

IS-2182: arbeidstaker-api

---

src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt

https://nav-it.slack.com/archives/G012X72TL12/p1731330287787359

IS-2779: Give access to mulighetsrommet-api (systemtoken)

---

src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/OppfolgingstilfelleService.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/api/OppfolgingstilfellePersonApi.kt
src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/database/OppfolgingstilfellePersonQuery.kt
src/test/kotlin/no/nav/syfo/application/api/PodApiSpek.kt
src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleApiSpek.kt
src/test/kotlin/testhelper/generator/GenerateOppfolgingstilfellePerson.kt

Reverterer https://github.com/navikt/isoppfolgingstilfelle/pull/198 som førte til problemer med connections mot databasen og restarts av appen i produksjon.

Revert IS-2782

---

src/main/resources/db/migration/R__grant_to_cloudsqliamuser.sql
src/main/resources/db/migration/V3_0__dvh_user.sql

I praksis skal de lese replica'en, men grant'en må  gjøres i primær-instansen.

IS-2881: Dvh lese tilgang

---

src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/api/OppfolgingstilfellePersonApi.kt

Litt logging og måling av kallet som timer ut innimellom, ref https://trello.com/c/fdQcI5DN/2872-channelwriteexception-i-isoppfolgingstilfelle

IS-2872: Add timing and logging
