navikt/isoppfolgingstilfelle

- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/OppfolgingstilfelleService.kt
- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleApi.kt
- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/Oppfolgingstilfellebit.kt
- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/domain/Oppfolgingstilfelle.kt
- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/domain/OppfolgingstilfelleDag.kt
- src/main/kotlin/no/nav/syfo/util/ListContainsPredicate.kt
- src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/OppfolgingstilfelleServiceSpek.kt
- src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleApiSpek.kt
- src/test/kotlin/testhelper/UserConstants.kt
- src/test/kotlin/testhelper/generator/OppfolgingstilfelleBitGenerator.kt
Add logic to take a list of OppfolgingstilfelleBit and group them into a list of Oppfolgingstilfelle based on a set of rules. The list of OppfolgingstilfelleBit create a timeline of days, where each day has a most significant Oppfolgingstilfelle found by using the Tag prioritization. Each day in the timeline is either a Arbeidsdag, Ferie or else a Sykedag.
The days are grouped into a list of Oppfolgingstilfelle based on the ordering of these three types.
> Group OppfolgingstilfelleBitList into OppfolgingstilfelleList

- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/kafka/OppfolgingstilfellePersonProducer.kt
Use UUID based on PersonIdent to ensure that records for a given PersonIdent ends up on the same Kafka partition
> Key of OppfolgingstilfellePerson to a UUID created from PersonIdent

- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/domain/Oppfolgingstilfellebit.kt
- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/domain/OppfolgingstilfelleDag.kt
- src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/OppfolgingstilfelleBitSpek.kt
Slik det har vært til nå har oppfølgingstilfeller ikke inkludert alle relevante virksomheter. Konsekvensen av det er en potensielt ufullstendig liste over mulige virksomheter når man skal kalle inn til dialogmøte. I tillegg kan det være umulig for nærmeste leder å svare på møtebehov. Begge deler bør løse seg ved endringen i denne PR'en.
> Collect all virksomheter into oppfolgingstilfelle

- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/domain/Oppfolgingstilfellebit.kt
- src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/OppfolgingstilfelleBitSpek.kt
Vi fikk en jira-sak der ettersendt sykmelding (med manglende virksomhetsnummer) har overstyrt tidligere innkomne søknader (med virksomhetsnummer). Dette kan gjøre at arbeidstakere ikke blir kandidater, samt at innkalling til dialogmøter ikke fungerer så godt.
> Bugfix tilfellebit-prioritering

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- src/main/kotlin/no/nav/syfo/App.kt
- src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
- src/main/kotlin/no/nav/syfo/application/cronjob/Cronjob.kt
- src/main/kotlin/no/nav/syfo/application/cronjob/CronjobModule.kt
- src/main/kotlin/no/nav/syfo/application/cronjob/CronjobResult.kt
- src/main/kotlin/no/nav/syfo/application/cronjob/CronjobRunner.kt
- src/main/kotlin/no/nav/syfo/client/HttpClientCommon.kt
- src/main/kotlin/no/nav/syfo/client/leaderelection/LeaderPodClient.kt
- src/main/kotlin/no/nav/syfo/client/leaderelection/LeaderPodDTO.kt
- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/OppfolgingstilfelleBitService.kt
- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/cronjob/OppfolgingstilfelleCronjob.kt
- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/database/OppfolgingstilfelleBitQuery.kt
- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/domain/Oppfolgingstilfellebit.kt
- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/kafka/KafkaSyketilfellebitService.kt
- src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleApiSpek.kt
- src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleSystemApiSpek.kt
- src/test/kotlin/testhelper/TestEnvironment.kt
Definerer ny cronjob som skal lage oppfolgingstilfeller i stedet for at disse lages med det samme man leser tilfellebitene fra Kafka. Togglet ut i første omgang i produksjon, skal teste at det oppfører seg som forventet på dev-gcp.
Skriver om testene i neste PR (slik at det er det som skjer i cronjob'en som testes i stedet for prosesseringen fra Kafka som blir mye enklere når cronjob'en tar over).
> Cronjob tilfelle

- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/domain/Oppfolgingstilfellebit.kt
- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/kafka/KafkaSyketilfellebit.kt
- src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleApiSpek.kt
- src/test/kotlin/testhelper/generator/KafkaSyketilfellebitGenerator.kt
Flex begynner å sende disse snart så vi må klare å leste dem fra Kafka. Men i første omgang filtrerer vi dem ut slik at de ikke spiller noen rolle for hvordan vi lager oppfølgingstilfeller.
> Inntektsmelding

- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/domain/Oppfolgingstilfellebit.kt
- src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/OppfolgingstilfelleBitSpek.kt
Ser at vi får noen lange oppfølgingstilfeller fordi arbeidstaker har registrert søknad med tag UTDANNING. Disse skal ikke være med i beregningen av oppfølgingstilfelle.
Dette har endret seg med en bugfix tidligere i uka, så PR'en nå endrer oppførselen med hensyn til dette tilbake til slik det var for noen dager siden.
> Filtrer bort biter som ikke skal brukes

- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/domain/Oppfolgingstilfellebit.kt
- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/domain/OppfolgingstilfelleDag.kt
- src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/OppfolgingstilfelleBitSpek.kt
Dette gjør at virksomhetsnumrene på oppfølgingstilfellet blir de arbeidstakeren har valgt ved innsending. Men hvis den lista blir tom bruker vi også de som vi har hentet fra aareg for sykmelding-ny-biter.
> Only use orgnr from sykmelding-ny if necessary

- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/domain/Oppfolgingstilfellebit.kt
- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/kafka/KafkaConfig.kt
- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/kafka/KafkaSyketilfellebit.kt
- src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleApiSpek.kt
Dette gjør at tilfellebiter med tag inntektsmelding inngår i det som brukes for å lage oppfølgingstilfeller. Dagene regnes som sykedager, og virksomhetsnummeret blir med i lista over orgnr til oppfølgingstilfellet - dette er vesentlig når vi får oppfølgingstilfeller basert på sykmelding-ny siden vi da bare har orgnr hentet fra aareg.
> Use inntektsmelding

- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/domain/OppfolgingstilfelleDag.kt
- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/metric/OppfolgingstilfelleMetric.kt
Telle opp og logge info om de oppfølgingstilfellene som opprettes som bare er basert på sykmelding-ny (+ inntektsmelding).
> Log sykmelding ny

- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/domain/OppfolgingstilfelleDag.kt
- src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/OppfolgingstilfelleBitSpek.kt
Likestille sykmelding med tag BEHANDLINGSDAGER med tilsvarende sykepengesøknad. Slik det er nå vil det ofte lages et langt oppfølgingstilfelle basert på sykmeldingen, som så endres når sykepengesøknaden(e) kommer.
> sykmelding med behandlingsdager skal ikke telle som sykedager

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
Tenker å hente siste oppfølgingstilfelle via api i stedet for å bruke det som lagres i isdialogmotekandidat.
> Grant access to api from isdialogmotekandidat

- src/main/resources/db/migration/V2_2__korriger_sykmelding.sql
Korrigerer tom for en sykmelding-bit som var blitt feil (slik at arbeidstaker får et mye lengre oppfølgingstilfelle enn det det faktisk er). Setter processed=false på den siste tilfelle-biten for den aktuelle personen for å trigge generering av et nytt og korrigert oppfølgingstilfelle.
> Korrigerer sykmelding med feil tom

- build.gradle.kts
- src/main/avro/Personhendelse.avdl
- src/main/avro/doedsfall/Doedsfall.avdl
- src/main/kotlin/no/nav/syfo/App.kt
- src/main/kotlin/no/nav/syfo/personhendelse/PersonhendelseService.kt
- src/main/kotlin/no/nav/syfo/personhendelse/db/PersonhendelseQueries.kt
- src/main/kotlin/no/nav/syfo/personhendelse/kafka/KafkaPersonhendelseConsumerConfig.kt
- src/main/kotlin/no/nav/syfo/personhendelse/kafka/KafkaPersonhendelseConsumerService.kt
- src/main/kotlin/no/nav/syfo/personhendelse/kafka/KafkaPersonhendelseTask.kt
- src/main/kotlin/no/nav/syfo/util/RequestUtil.kt
- src/main/resources/db/migration/R__grant_to_cloudsqliamuser.sql
- src/main/resources/db/migration/V2_3__create_table_person.sql
- src/test/kotlin/no/nav/syfo/personhendelse/KafkaPersonhendelseConsumerServiceSpek.kt
- src/test/kotlin/no/nav/syfo/personhendelse/PersonhendelseServiceSpek.kt
- src/test/kotlin/testhelper/TestDatabase.kt
- src/test/kotlin/testhelper/generator/GenerateOppfolgingstilfellePerson.kt
- src/test/kotlin/testhelper/generator/KafkaPersonhendelseDTOGenerator.kt
I første omgang lagrer dette relevante dødsfall, dvs for personident'er der vi har oppfølgingstilfeller i databasen. I neste PR tenkte jeg å legge til dodsdato som et felt i oppfølgingstilfelle-dto'ene som brukes på Kafka-topic og som returneres i rest-api.
> Consumer for personhendelser

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
GCP advarer om at ram-bruken er høy, så vi bør allokere mer. Verdien man setter på være en multippel av 256.
> Resize prod-db (more ram)

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- src/main/kotlin/no/nav/syfo/App.kt
- src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
- src/main/kotlin/no/nav/syfo/identhendelse/IdenthendelseService.kt
- src/test/kotlin/no/nav/syfo/identhendelse/IdenthendelseServiceSpek.kt
- src/test/kotlin/testhelper/TestEnvironment.kt
Dette blir samme case som i `syfooversiktsrv` (ettersom at tilfellene der har kommet herfra). Der var det 11 (av 10 millioner) man måtte manuelt skippe, så vi får se hvordan det går denne gangen 😬
> Skip processing of non-updated identer and enable identhendelser in prod

- src/main/kotlin/no/nav/syfo/identhendelse/IdenthendelseService.kt
- src/test/kotlin/no/nav/syfo/identhendelse/IdenthendelseServiceSpek.kt
Venter på at den skal kjøre gjennom de historiske identhendelsene før denne kan "endre tilbake" igjen.
> Throw error when ny ident not updated in pdl-api

- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/domain/OppfolgingstilfelleDag.kt
- src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/OppfolgingstilfelleBitSpek.kt
Vi må filtrere ut virksomheter som ikke har noen oppfolgingstilfelle-dager i det aktuelle tilfellet før vi finner graderings-bit per virksomhet.
> Virksomhet uten biter i tilfellet skal ikke telle i gradert-sjekk

- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/domain/Oppfolgingstilfellebit.kt
- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/domain/OppfolgingstilfelleDag.kt
- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/domain/OppfolgingstilfellePerson.kt
- src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/OppfolgingstilfelleBitSpek.kt
Make 100% sykmeldt tag higher priority than gradert. So if any virksomhet INGEN_AKTIVITET bit for last day it will be the priorityGraderingBit (regardles of intruffet tidspunkt), and aktivitetskrav will be created.
> Check gradering of last day in tilfelle, not per virksomhet

- src/main/resources/db/migration/V2_6__remove_incorrect_soknad.sql
Delete entire bit because the correct part of the soknad, with expected fom/tom, is a seperate bit. Reprocess newest bit to regenerate tilfelle.
https://jira.adeo.no/browse/FAGSYSTEM-270352
> Remove incorrect soknad bit

- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/domain/OppfolgingstilfellePerson.kt
- src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/OppfolgingstilfelleBitSpek.kt
I noen hjørnetilfeller der sykmeldinger har startdato i framtiden kan det bli sånn at varigheten i uker blir negativ slik vi kalkulerer det nå. Så bedre å defaulte til 0 i disse tilfellene, og så får vi se nærmere på dem hvis det dukker opp i praksis.
> IS-1864: Unngå negative varigheter

- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/domain/OppfolgingstilfelleDag.kt
- src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/OppfolgingstilfelleBitSpek.kt
For sykmeldinger med reisetilskudd er den sykmeldte på jobb (så lenge de får reisetilskudd), derfor må vi ikke telle disse dagene som sykedager.
> Don't count reisetilskudd as sykedag

- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/OppfolgingstilfelleService.kt
- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/api/OppfolgingstilfellePersonApi.kt
- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/database/OppfolgingstilfellePersonQuery.kt
- src/test/kotlin/no/nav/syfo/application/api/PodApiSpek.kt
- src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleApiSpek.kt
- src/test/kotlin/testhelper/generator/GenerateOppfolgingstilfellePerson.kt
Forsøk på å fikse sporadiske feil i isoppfolgingstilfelle i loggene - Se https://trello.com/c/fdQcI5DN/2872-channelwriteexception-i-isoppfolgingstilfelle.
Skrevet om spørringen som henter oppfolgingstilfeller for en liste av personer til å gjøre alt i én spørring mot databasen ved bruk av `personident = ANY (string_to_array(?, ','))` som vi har gjort i andre bulk-endepunkter. Håpet er at kall til endepunktet går raskere enn når man gjør én db-spørring per person.
> IS-2782: Get oppfolgingstilfeller for persons in one db-query

- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/person/database/OppfolgingstilfellePersonQuery.kt
- src/test/kotlin/no/nav/syfo/oppfolgingstilfelle/api/OppfolgingstilfelleApiSpek.kt
- src/test/kotlin/testhelper/generator/GenerateOppfolgingstilfellePerson.kt
Vi tar alltid første elementet i lista fra spørringen så kan legge på LIMIT 1 her for å unngå unødvendig mapping til objekter
> IS-2872: Add limit to query and improve test

- src/main/resources/db/migration/V3_3__fix_long_sykmelding_again.sql
Må reprosessere siste tilfelle_bit for den aktuelle personen for at det nye oppfølgingstilfellet (med korrigert tildato) blir det som gjelder.
https://jira.adeo.no/browse/FAGSYSTEM-374288
> IS-3192: Korrigere oppfølgingstilfelle (nytt forsøk)

- src/main/kotlin/no/nav/syfo/oppfolgingstilfelle/bit/cronjob/SykmeldingNyCronjob.kt
Uheldig å gjøre kall mot `aareg` inni en db-transaksjon (som da blir mye mer langvarig enn nødvendig)
> IS-3334: Korte inn db-transaksjon

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
Dette trengs for å spørre isoppfolgingstilfelle om nå-tilstanden på en sykmeldt på stoppunktsdatoen. Det er viktig å sjekke at personen fortsatt er sykmeldt på det gitte tidspunktet, i tillegg til om de er sykmeldt fra en virksomhet eller ikke. Skal bruke system-APIet til dette.
> IS-3397: Allow ismeroppfolging API access

- src/main/resources/db/migration/V3_5__delete_incorrect_oppfolgingstilfelle.sql
Rydder opp etter en feilregistrert sykmelding (se Trello/Jira-sak).
tilfelle_bit'ene ble automatisk flyttet til `tilfelle_bit_deleted` da tombstone'n ble prosessert fra Kafka. Men siden det ikke fantes noen tidligere biter ble forekomstene i `oppfolgingstilfelle_person` liggende igjen. Sletter dem med et sql-script.
> IS-3443: Slette feilregistrert oppfolgingstilfelle
